EXEC SaldoCxCyP
ALTER TABLE Compra ENABLE TRIGGER SaldoCxCActualiza
ALTER TABLE Compra ENABLE TRIGGER SaldoCxCBorrar
ALTER TABLE Compra ENABLE TRIGGER SaldoCxCInserta
ALTER TABLE DetCompra ENABLE TRIGGER SaldoCosto
ALTER TABLE Pago ENABLE TRIGGER PagoActualiza
ALTER TABLE Pago ENABLE TRIGGER PagoBorra
ALTER TABLE OrdenProduccionDetalle ENABLE TRIGGER ActualizaDetCompra
ALTER TABLE OrdenProduccion ENABLE TRIGGER CreaCompra
ALTER TABLE OrdenProduccion ENABLE TRIGGER CambiaCompraOP
ALTER TABLE OrdenProduccion ENABLE TRIGGER BorraCompraOP
ALTER TABLE Retencion ENABLE TRIGGER RetencionBorra
ALTER TABLE Retencion ENABLE TRIGGER RetencionActualiza
