
ALTER TRIGGER [ASIENTOBORRA] ON [ASIENTO] FOR DELETE AS
IF EXISTS(SELECT * FROM SETEO WHERE ISNULL(ELIMINAASIENTO, 1) = 0)
BEGIN
	RAISERROR ('NO SE PUEDE ELIMINAR ASIENTOS. BLOQUEADO EN PROPIEDADES GENERALES', 16, 1)
	ROLLBACK TRANSACTION
	RETURN 
END

DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
SELECT @VIDUNICA = DELETED.IDASIENTO FROM DELETED
SELECT @VCOD = DELETED.CODASIENTO FROM DELETED
INSERT INTO AUDITORIA (IDTIPOAUDITA, IDAUDITAESTADO, IDUNICA, CODIGO)
VALUES (23, 4, @VIDUNICA, @VCOD)
GO

ALTER TRIGGER [AUDITABORRAPERSONAL] ON [PERSONAL] FOR DELETE AS
DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
SELECT @VIDUNICA = DELETED.IDPERSONAL FROM DELETED
SELECT @VCOD = DELETED.NOMBRE FROM DELETED
INSERT INTO AUDITORIA 
(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA)
VALUES (35, 4, @VCOD, @VIDUNICA)
GO

ALTER TRIGGER [AUDITABORRARESERVACION] ON [RESERVACION] FOR DELETE AS
DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
SELECT @VIDUNICA = DELETED.IDRESERVACION FROM DELETED
SELECT @VCOD = DELETED.NUMERO FROM DELETED
INSERT INTO AUDITORIA 
(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA)
VALUES (39, 4, @VCOD, @VIDUNICA)
GO

ALTER TRIGGER [AUDITACOMPRANUMEROEDITA] ON [ORDENMOVILIZACION] FOR UPDATEAS
DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
SELECT @VIDUNICA = INSERTED.IDMOVILIZACION FROM INSERTED
SELECT @VCOD = ARTICULO.CODIGO FROM INSERTED INNER JOIN ARTICULO
ON ARTICULO.IDARTICULO = INSERTED.IDARTICULO
------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'ORDENMOVILIZACION'
	Set @VCLAVE = 'IDMOVILIZACION'
	Set @vEstado = 2
	Set @vIdTipo = 32
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------
GO

ALTER TRIGGER [AUDITACOMPRANUMEROINSERTA] ON [COMPRANUMERO] FOR INSERTAS
return
GO

ALTER TRIGGER [AUDITAFACTURANUMEROBORRA] ON [FACTURANUMERO] FOR DELETEAS 
DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
SELECT @VIDUNICA = DELETED.IDFACTURANOMBRE, @VCOD = DELETED.ESTACION FROM DELETED
INSERT INTO AUDITORIA 
(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA)
VALUES (52, 4, @VCOD, @VIDUNICA)
GO

ALTER TRIGGER [AUDITAFACTURANUMEROEDITA] ON [FACTURANUMERO] FOR UPDATE, INSERT ASSET NOCOUNT ON;
------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VIDUNICA = i.IDFACTURANOMBRE, @VCOD = i.ESTACION FROM INSERTED i

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'FACTURANUMERO'
	Set @VCLAVE = 'IDFACTURANOMBRE'
	Set @vEstado = 2
	If Update(IDFACTURANOMBRE) Set @vEstado = 1
	Set @vIdTipo = 52
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------
GO

ALTER TRIGGER [AUDITAFACTURANUMEROINSERTA] ON [FACTURANUMERO] FOR INSERTAS 
return
GO

ALTER TRIGGER [AUDITANUEVACC] ON [CUENTACORRIENTE] FOR INSERTAS
------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
	SELECT @VIDUNICA = IDCUENTACORRIENTE, @VCOD = INSERTED.NUMCUENTA FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'CUENTACORRIENTE'
	Set @VCLAVE = 'IDCUENTACORRIENTE'
	Set @vEstado = 2
	If Update(IDCUENTACORRIENTE) Set @vEstado = 1
	Set @vIdTipo = 28
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------
GO

ALTER TRIGGER [AUDITANUEVACUENTA] ON [CUENTA] FOR INSERTAS
return
GO

ALTER TRIGGER [AUDITAORDENMOVINSERTA] ON [ORDENMOVILIZACION] FOR INSERTAS
------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VCOD = ARTICULO.CODIGO, @VIDUNICA = IDMOVILIZACION 
		FROM INSERTED INNER JOIN ARTICULO
		ON ARTICULO.IDARTICULO = INSERTED.IDARTICULO

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'ORDENMOVILIZACION'
	Set @VCLAVE = 'IDMOVILIZACION'
	Set @vEstado = 2
	If Update(IDMOVILIZACION) Set @vEstado = 1
	Set @vIdTipo = 28
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------
GO

ALTER TRIGGER [AUDITAPAGOLOTEEDITA] ON [PAGOLOTE]FOR UPDATEAS
DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
SELECT @VIDUNICA = INSERTED.IDPAGOLOTE FROM INSERTED
SELECT @VCOD = INSERTED.CODIGO FROM INSERTED

DECLARE @BAUDITA BIT
SELECT @BAUDITA = ISNULL(AUDITORIA, 0) FROM SETEO
IF @BAUDITA = 0 RETURN

Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
Set @VTABLA = 'PAGOLOTE'
Set @VCLAVE = 'IDPAGOLOTE'
Set @vEstado = 2
Set @vIdTipo = 34
SET @IDCOL = 1
SET @IDPOS = 1
SET @IDCOLN = 1

SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
WHILE @VCOL IS NOT NULL
BEGIN
	IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS' --AND SUBSTRING(@VCOL,1,8) <>'FECHAEDI'
	BEGIN
	SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
	' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
	+ CAST(@VIDUNICA AS VARCHAR(20))
	EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
	IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
		INSERT INTO AUDITORIA 
		(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
		VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
	END
	SET @IDCOL = @IDCOL * 2
	SET @IDCOLN = @IDCOLN + 1
	IF @IDCOL >= 256     
	BEGIN
	SET @IDCOL = 1
	SET @IDPOS = @IDPOS + 1
	END
	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
END
GO

ALTER TRIGGER [AUDITAPAGOLOTEINSERTA] ON [PAGOLOTE]FOR INSERTAS
DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
SELECT @VIDUNICA = INSERTED.IDPAGOLOTE, @VCOD = INSERTED.CODIGO FROM INSERTED

DECLARE @BAUDITA BIT
SELECT @BAUDITA = ISNULL(AUDITORIA, 0) FROM SETEO
IF @BAUDITA = 0 RETURN

Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
Set @VTABLA = 'PAGOLOTE'
Set @VCLAVE = 'IDPAGOLOTE'
Set @vEstado = 1
Set @vIdTipo = 34
SET @IDCOL = 1
SET @IDPOS = 1
SET @IDCOLN = 1

SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
WHILE @VCOL IS NOT NULL
BEGIN
	IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS' --AND SUBSTRING(@VCOL,1,8) <>'FECHAEDI'
	BEGIN
	SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
	' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
	+ CAST(@VIDUNICA AS VARCHAR(20))
	EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
	IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
		INSERT INTO AUDITORIA 
		(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
		VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
	END
	SET @IDCOL = @IDCOL * 2
	SET @IDCOLN = @IDCOLN + 1
	IF @IDCOL >= 256     
	BEGIN
	SET @IDCOL = 1
	SET @IDPOS = @IDPOS + 1
	END
	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
END
GO

ALTER TRIGGER [AUDITAPERSONALEDITA] ON [PERSONAL]FOR UPDATE, INSERT ASset nocount on
------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
	SELECT @VIDUNICA = idPersonal, @VCOD = INSERTED.NOMBRE FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'PERSONAL'
	Set @VCLAVE = 'IDPERSONAL'
	Set @vEstado = 2
	If Update(IDPERSONAL) Set @vEstado = 1
	Set @vIdTipo = 35
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------
GO

ALTER TRIGGER [AUDITAPERSONALINSERTA] ON [PERSONAL]FOR INSERTAS
return
GO

ALTER TRIGGER [AUDITARESERVAEDITA] ON [RESERVACION]FOR UPDATEAS
------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VCOD = Numero, @VIDUNICA = IDRESERVACION FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'RESERVACION'
	Set @VCLAVE = 'IDRESERVACION'
	Set @vEstado = 2
	If Update(IDRESERVACION) Set @vEstado = 1
	Set @vIdTipo = 39
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------
GO

ALTER TRIGGER [AUDITARESERVAINSERTA] ON [RESERVACION]FOR INSERTAS
------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VCOD = Numero, @VIDUNICA = IDRESERVACION FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'RESERVACION'
	Set @VCLAVE = 'IDRESERVACION'
	Set @vEstado = 2
	If Update(IDRESERVACION) Set @vEstado = 1
	Set @vIdTipo = 39
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------




GO

ALTER TRIGGER [AUDITOBORRAPAGOLOTE] ON [PAGOLOTE] FOR DELETE AS
DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
SELECT @VIDUNICA = DELETED.IDPAGOLOTE FROM DELETED
SELECT @VCOD = INSERTED.CODIGO FROM INSERTED
INSERT INTO AUDITORIA 
(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA)
VALUES (34, 4, @VCOD, @VIDUNICA)
GO

ALTER TRIGGER [AUDITORIAASIENTODETE] ON [ASIENTODETALLE] FOR UPDATE, INSERT AS------- Auditoria -----------
IF NOT EXISTS(SELECT * FROM SETEO WHERE ISNULL(AUDITORIADETALLE, 0) = 1
	AND ISNULL(AUDITORIA, 0) = 1) RETURN
Begin
	DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
	SELECT @VIDUNICA = i.IDDETASIENTO, @VCOD = Cast(i.idCuenta as nvarchar(10)) FROM INSERTED i

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'ASIENTODETALLE'
	Set @VCLAVE = 'IDDETASIENTO'
	Set @vEstado = 2
	If Update(IDDETASIENTO) Set @vEstado = 1
	Set @vIdTipo = 50
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------
GO

ALTER TRIGGER [AUDITORIAASIENTODETI] ON [ASIENTODETALLE] FOR INSERT ASIF NOT EXISTS(SELECT AUDITORIADETALLE FROM SETEO WHERE ISNULL(AUDITORIADETALLE, 0) = 1
	AND ISNULL(AUDITORIA, 0) = 1) RETURN
DECLARE @VIDUNICA INT, @CODPADRE INT
SELECT @VIDUNICA = INSERTED.IDDETASIENTO, 
@CODPADRE = CAST(INSERTED.IDASIENTO AS NVARCHAR(20)) FROM INSERTED

DECLARE @BAUDITA BIT
SELECT @BAUDITA = ISNULL(AUDITORIA, 0) FROM SETEO
IF @BAUDITA = 0 RETURN

Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
Set @VTABLA = 'ASIENTODETALLE'
Set @VCLAVE = 'IDDETASIENTO'
Set @vEstado = 1
Set @vIdTipo = 50
SET @IDCOL = 1
SET @IDPOS = 1
SET @IDCOLN = 1

SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
WHILE @VCOL IS NOT NULL
BEGIN
	IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS' --AND SUBSTRING(@VCOL,1,8) <>'FECHAEDI'
	BEGIN
	SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
	' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
	+ CAST(@VIDUNICA AS VARCHAR(20))
	EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
	IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
		INSERT INTO AUDITORIA 
		(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
		VALUES (@VIDTIPO, @VESTADO, @CodPadre, @VIDUNICA, @VCOL, @VSALIDA)
	END
	SET @IDCOL = @IDCOL * 2
	SET @IDCOLN = @IDCOLN + 1
	IF @IDCOL >= 256     
	BEGIN
	SET @IDCOL = 1
	SET @IDPOS = @IDPOS + 1
	END
	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
END
GO

ALTER TRIGGER [AUDITORIAASIENTOE] ON [ASIENTO] FOR UPDATE, INSERT AS------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
	SELECT @VIDUNICA = i.IDASIENTO, @VCOD = i.CODASIENTO FROM INSERTED i

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'ASIENTO'
	Set @VCLAVE = 'IDASIENTO'
	Set @vEstado = 2
	If Update(IDASIENTO) Set @vEstado = 1
	Set @vIdTipo = 23
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------
GO

ALTER TRIGGER [AUDITORIAASIENTOTIPOEDITA] ON [ASIENTOTIPO]FOR UPDATEAS
------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VCOD = Numero, @VIDUNICA = IDTIPOASIENTO FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'ASIENTOTIPO'
	Set @VCLAVE = 'IDTIPOASIENTO'
	Set @vEstado = 2
	If Update(IDTIPOASIENTO) Set @vEstado = 1
	Set @vIdTipo = 47
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------




GO

ALTER TRIGGER AUDITORIABORRA ON DBO.ARTICULO FOR DELETE AS
DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
SELECT @VIDUNICA = DELETED.IDARTICULO FROM DELETED
SELECT @VCOD = DELETED.CODIGO FROM DELETED
INSERT INTO AUDITORIA 
(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA)
VALUES (24, 4, @VCOD, @VIDUNICA)

GO

ALTER TRIGGER [AUDITORIABORRA1] ON [DBO].[ARTICULOSRI] FOR DELETE AS
DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
SELECT @VIDUNICA = DELETED.IDARTICULOSRI FROM DELETED
SELECT @VCOD = DELETED.CODIGO FROM DELETED
INSERT INTO AUDITORIA 
(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA)
VALUES (58, 4, @VCOD, @VIDUNICA)


GO

ALTER TRIGGER AUDITORIABORRAGRUPOART ON DBO.ARTICULOGRUPO FOR DELETE AS
DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
SELECT @VIDUNICA = DELETED.IDGRUPOARTICULO FROM DELETED
SELECT @VCOD = DELETED.GRUPO FROM DELETED
INSERT INTO AUDITORIA 
(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA)
VALUES (29, 4, @VCOD, @VIDUNICA)

GO

ALTER TRIGGER [AUDITORIACCBORRA] ON [CUENTACORRIENTE] FOR DELETE AS
DECLARE @VIDUNICA INT, @VCOD VARCHAR(20), @VTIPO INT
SELECT @VIDUNICA = DELETED.IDCUENTACORRIENTE FROM DELETED
SELECT @VCOD = DELETED.NUMCUENTA FROM DELETED

INSERT INTO AUDITORIA 
(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA)
VALUES (28, 4, @VCOD, @VIDUNICA)
GO

ALTER TRIGGER [AUDITORIACLIENTEBORRA] ON DBO.CLIENTE FOR DELETE AS
DECLARE @VIDUNICA INT, @VCOD VARCHAR(20), @VTIPO INT
SELECT @VIDUNICA = DELETED.IDCLIENTE FROM DELETED
SELECT @VCOD = DELETED.NOMBRE FROM DELETED
SELECT @VTIPO = PROVEEDOR FROM DELETED
SET @VTIPO = 25 + @VTIPO

INSERT INTO AUDITORIA 
(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA)
VALUES (@VTIPO, 4, @VCOD, @VIDUNICA)
GO

ALTER TRIGGER [AUDITORIACLIENTEE] ON DBO.CLIENTE FOR INSERT, UPDATEAS
return
GO

ALTER TRIGGER [AUDITORIACLIENTEGRUPOBORRA] ON [CLIENTEGRUPO] FOR DELETE AS
DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
SELECT @VIDUNICA = DELETED.IDGRUPOCLIENTE FROM DELETED
SELECT @VCOD = DELETED.GRUPO FROM DELETED
INSERT INTO AUDITORIA 
(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA)
VALUES (30, 4, @VCOD, @VIDUNICA)
GO

ALTER TRIGGER [AUDITORIACLIENTEGRUPOE] ON [CLIENTEGRUPO]FOR UPDATE AS
------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VCOD = GRUPO, @VIDUNICA = IDGRUPOCLIENTE FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'CLIENTEGRUPO'
	Set @VCLAVE = 'IDGRUPOCLIENTE'
	Set @vEstado = 2
	If Update(IDGRUPOCLIENTE) Set @vEstado = 1
	Set @vIdTipo = 30
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------




GO

ALTER TRIGGER [AUDITORIACLIENTEGRUPOI] ON [CLIENTEGRUPO]FOR INSERTAS
------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VCOD = GRUPO, @VIDUNICA = IDGRUPOCLIENTE FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'CLIENTEGRUPO'
	Set @VCLAVE = 'IDGRUPOCLIENTE'
	Set @vEstado = 2
	If Update(IDGRUPOCLIENTE) Set @vEstado = 1
	Set @vIdTipo = 30
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------




GO

ALTER TRIGGER [AUDITORIACLIENTEI] ON DBO.CLIENTE FOR INSERT, UPDATEAS
------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VIDUNICA INT, @VTIPO INT, @VCOD VARCHAR(20)
	SELECT @VIDUNICA = i.IDCLIENTE, @VTIPO = i.PROVEEDOR, @VCOD = i.NOMBRE FROM INSERTED i
	SET @VTIPO = 25 + @VTIPO

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'CLIENTE'
	Set @VCLAVE = 'IDCLIENTE'
	Set @vEstado = 2
	If Update(IdCliente) Set @vEstado = 1
	Set @vIdTipo = @vTipo
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------
GO

ALTER TRIGGER [AUDITORIACOMPRANUMEROBORRA] ON [COMPRANUMERO]FOR DELETE AS
DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
SELECT @VIDUNICA = DELETED.IDTIPOFACTURA FROM DELETED
SELECT @VCOD = DELETED.NOMBRE FROM DELETED
INSERT INTO AUDITORIA 
(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA)
VALUES (31, 4, @VCOD, @VIDUNICA)
GO

ALTER TRIGGER [AUDITORIACOMPRANUMEROEDITA] ON [COMPRANUMERO] FOR UPDATE, INSERTAS
------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
	SELECT @VIDUNICA = i.IDTIPOFACTURA, @VCOD = i.NOMBRE FROM INSERTED i

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'COMPRANUMERO'
	Set @VCLAVE = 'IDTIPOFACTURA'
	Set @vEstado = 2
	Set @vIdTipo = 31
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------
GO

ALTER TRIGGER [AUDITORIACUENTABORRA] ON [CUENTA] FOR DELETE AS
DECLARE @VIDUNICA INT, @VCOD VARCHAR(20), @VTIPO INT
SELECT @VIDUNICA = DELETED.IDCUENTA FROM DELETED
SELECT @VCOD = DELETED.CODIGO FROM DELETED

INSERT INTO AUDITORIA 
(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA)
VALUES (27, 4, @VCOD, @VIDUNICA)
GO

ALTER TRIGGER AUDITORIAEDITA ON DBO.ARTICULO FOR UPDATEAS
------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VCOD = ARTICULO, @VIDUNICA = IDARTICULO FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'ARTICULO'
	Set @VCLAVE = 'IDARTICULO'
	Set @vEstado = 2
	If Update(IDARTICULO) Set @vEstado = 1
	Set @vIdTipo = 24
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------

GO

ALTER TRIGGER [AUDITORIAEDITA1] ON [DBO].[ARTICULOSRI] FOR UPDATEAS
------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VCOD = CODIGO, @VIDUNICA = IDARTICULOSRI FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'ARTICULOSRI'
	Set @VCLAVE = 'IDARTICULOSRI'
	Set @vEstado = 2
	If Update(IDARTICULOSRI) Set @vEstado = 1
	Set @vIdTipo = 58
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------
GO

ALTER TRIGGER [AUDITORIAEDITACC] ON [CUENTACORRIENTE] FOR UPDATEAS
------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VCOD = NUMCUENTA, @VIDUNICA = IDCUENTACORRIENTE FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'CUENTACORRIENTE'
	Set @VCLAVE = 'IDCUENTACORRIENTE'
	Set @vEstado = 2
	If Update(IDCUENTACORRIENTE) Set @vEstado = 1
	Set @vIdTipo = 58
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------




GO

ALTER TRIGGER [AUDITORIAEDITACUENTA] ON [CUENTA] FOR UPDATE, INSERT AS------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
	SELECT @VIDUNICA = i.IDCUENTA, @VCOD = i.CODIGO FROM INSERTED i

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'Cuenta'
	Set @VCLAVE = 'IdCuenta'
	Set @vEstado = 2
	If Update(IdCuenta) Set @vEstado = 1
	Set @vIdTipo = 27
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------
GO

ALTER TRIGGER AUDITORIAEDITAGRUPOART ON DBO.ARTICULOGRUPOFOR UPDATEAS
------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VCOD = Grupo, @VIDUNICA = IDGRUPOARTICULO FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'ARTICULOGRUPO'
	Set @VCLAVE = 'IDGRUPOARTICULO'
	Set @vEstado = 2
	If Update(IDGRUPOARTICULO) Set @vEstado = 1
	Set @vIdTipo = 29
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------
GO

ALTER TRIGGER AUDITORIANUEVO ON DBO.ARTICULO FOR INSERTAS
------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VCOD = Codigo, @VIDUNICA = IDARTICULO FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'ARTICULO'
	Set @VCLAVE = 'IDARTICULO'
	Set @vEstado = 2
	If Update(IDARTICULO) Set @vEstado = 1
	Set @vIdTipo = 24
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------

GO

ALTER TRIGGER [AUDITORIANUEVO1] ON [DBO].[ARTICULOSRI] FOR INSERTAS
------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VCOD = Codigo, @VIDUNICA = IDARTICULOSRI FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'ARTICULOSRI'
	Set @VCLAVE = 'IDARTICULOSRI'
	Set @vEstado = 2
	If Update(IDARTICULOSRI) Set @vEstado = 1
	Set @vIdTipo = 58
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------

GO

ALTER TRIGGER [AUDITORIANUEVOGRUPOART] ON [ARTICULOGRUPO]FOR INSERTAS
return
GO

ALTER TRIGGER [AUDITORIAORDENMOVBORRA] ON [ORDENMOVILIZACION]FOR DELETE AS
DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
SELECT @VIDUNICA = DELETED.IDMOVILIZACION FROM DELETED
SELECT @VCOD = ARTICULO.CODIGO FROM DELETED INNER JOIN ARTICULO
ON ARTICULO.IDARTICULO = DELETED.IDARTICULO
INSERT INTO AUDITORIA 
(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA)
VALUES (32, 4, @VCOD, @VIDUNICA)
GO

ALTER TRIGGER [AUDITORIAROLCONCEPTOBORRA] ON DBO.ROLCONCEPTO FOR DELETE AS
DECLARE @VIDUNICA INT, @VCOD VARCHAR(20), @VTIPO INT
SELECT @VIDUNICA = DELETED.IDROLCONCEPTO FROM DELETED
SELECT @VCOD = DELETED.CONCEPTO FROM DELETED

INSERT INTO AUDITORIA (IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA)
VALUES (55, 4, @VCOD, @VIDUNICA)
GO

ALTER TRIGGER [AUDITORIAROLCONCEPTOEDITA] ON DBO.ROLCONCEPTO FOR UPDATE AS------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VCOD = Concepto, @VIDUNICA = IDROLCONCEPTO FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'ROLCONCEPTO'
	Set @VCLAVE = 'IDROLCONCEPTO'
	Set @vEstado = 2
	If Update(IDROLCONCEPTO) Set @vEstado = 1
	Set @vIdTipo = 55
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------




GO

ALTER TRIGGER [AUDITORIAROLCONCEPTOINSERTA] ON DBO.ROLCONCEPTO FOR INSERT AS------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VCOD = Concepto, @VIDUNICA = IDROLCONCEPTO FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'ROLCONCEPTO'
	Set @VCLAVE = 'IDROLCONCEPTO'
	Set @vEstado = 2
	If Update(IDROLCONCEPTO) Set @vEstado = 1
	Set @vIdTipo = 55
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------




GO

ALTER TRIGGER [AUDITORIAROLPAGOBORRA] ON [ROLPAGO] FOR DELETE AS
DECLARE @VIDUNICA INT, @VCOD VARCHAR(20), @VTIPO INT
SELECT @VIDUNICA = DELETED.IDROLPAGO FROM DELETED
SELECT @VCOD = DELETED.NOMBRE FROM DELETED

INSERT INTO AUDITORIA 
(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA)
VALUES (54, 4, @VCOD, @VIDUNICA)
GO

ALTER TRIGGER [AUDITORIAROLPAGOEDITA] ON [ROLPAGO] FOR UPDATE AS------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VCOD = Nombre, @VIDUNICA = IDROLPAGO FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'ROLPAGO'
	Set @VCLAVE = 'IDROLPAGO'
	Set @vEstado = 2
	If Update(IDROLPAGO) Set @vEstado = 1
	Set @vIdTipo = 54
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------




GO

ALTER TRIGGER [AUDITORIAROLPAGOINSERTA] ON [ROLPAGO] FOR INSERT AS------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VCOD = Nombre, @VIDUNICA = IDROLPAGO FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'ROLPAGO'
	Set @VCLAVE = 'IDROLPAGO'
	Set @vEstado = 2
	If Update(IDROLPAGO) Set @vEstado = 1
	Set @vIdTipo = 54
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------




GO

ALTER TRIGGER [BORRAASIENTODET] ON [ASIENTODETALLE] FOR DELETE AS
Declare @vIdUnica Int, @vCod VarChar(20)
Select @vIdUnica = Deleted.idDetAsiento, @vCod = Asiento.CodAsiento From Deleted
Inner Join Asiento On Deleted.idAsiento = Asiento.idAsiento
INSERT INTO AUDITORIA 
(IDTIPOAUDITA, IDAUDITAESTADO, IDUNICA, CODIGO)
VALUES (50, 4, @VIDUNICA, @VCOD)
GO

ALTER TRIGGER [BORRACIUDAD] ON [CLIENTECIUDAD] FOR DELETE AS
DECLARE @ICUENTA INT, @CIUDAD CHAR(20), @ID INT
SELECT @CIUDAD = DELETED.CIUDAD, 
	@ID = DELETED.IDCIUDAD FROM DELETED

SELECT  @ICUENTA=COUNT(*) FROM CLIENTE 
WHERE CLIENTE.IDCIUDAD = @ID
IF @ICUENTA > 0
BEGIN
   RAISERROR ('EXISTEN %D REGISTROS RELACIONADOS. NO PUEDE BORRAR CIUDAD: %S', 
	16, 1, @ICUENTA, @CIUDAD)
   ROLLBACK TRANSACTION
END
GO

ALTER TRIGGER [BORRACOMPRAOP] ON [ORDENPRODUCCION]FOR DELETEAS
DECLARE @IDORDENPROD INT

SELECT @IDORDENPROD = DELETED.IDORDENPROD
FROM DELETED

DELETE COMPRA 
WHERE COMPRA.IDORDENPROD = @IDORDENPROD
GO

ALTER TRIGGER [BORRADETCOMPRA] ON DBO.DETCOMPRA FOR DELETE AS
DECLARE @VIDCOMPRA INT, @VCANTIDAD FLOAT, @VIDART INT, @VSIGNO INT, @VSALDO FLOAT,
 @ACTSALDO BIT, @ACTCOSTO BIT, @IDORIGEN INT

DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
SELECT @VIDUNICA = IDDETCOMPRA, @VCOD = COMPRA.NUMERO FROM DELETED
INNER JOIN COMPRA ON DELETED.IDCOMPRA = COMPRA.IDCOMPRA
INSERT INTO AUDITORIA 
(IDTIPOAUDITA, IDAUDITAESTADO, IDUNICA, CODIGO)
VALUES (51, 4, @VIDUNICA, @VCOD)

IF EXISTS(SELECT * FROM SERIE WHERE IDDETCOMPRA = @VIDUNICA)
BEGIN
	SELECT @IDORIGEN = IDORIGEN FROM SERIE WHERE IDDETCOMPRA = @VIDUNICA
	UPDATE SERIE SET DISPONIBLE = 1 WHERE IDSERIE = @IDORIGEN
	DELETE SERIE WHERE IDDETCOMPRA = @VIDUNICA
END

SELECT @ACTSALDO = ACTUALIZASALDO, @ACTCOSTO = ACTUALIZACOSTO FROM SETEOF
IF ISNULL(@ACTSALDO, 1) = 0 RETURN

IF EXISTS(SELECT * FROM COMPRA, INSERTED WHERE COMPRA.BORRAR = 1 
	AND COMPRA.IDCOMPRA = INSERTED.IDCOMPRA)
	RETURN

DECLARE CARTICULOS CURSOR LOCAL KEYSET FOR
	SELECT ISNULL(DC.CANTIDAD, 0), ISNULL(DC.IDARTICULO, 0)
	,DC.SIGNO
	FROM COMPRA C INNER JOIN DELETED DC ON 
	C.IDCOMPRA = DC.IDCOMPRA 
	WHERE (DC.SIGNO=1 OR DC.SIGNO=-1)
	AND DC.BORRAR = 0
	AND C.BORRAR = 0

OPEN CARTICULOS
FETCH NEXT FROM CARTICULOS INTO @VCANTIDAD, @VIDART, @VSIGNO
WHILE (@@FETCH_STATUS <> -1)
BEGIN
    IF (@@FETCH_STATUS <> -2)
    BEGIN
	UPDATE ARTICULO SET SALDO = SALDO - @VCANTIDAD * @VSIGNO
	WHERE IDARTICULO = @VIDART
    END
    FETCH NEXT FROM CARTICULOS INTO @VCANTIDAD, @VIDART, @VSIGNO
END
CLOSE CARTICULOS
DEALLOCATE CARTICULOS
GO

ALTER TRIGGER [CAMBIACOMPRAOP] ON [ORDENPRODUCCION]FOR UPDATEAS
DECLARE @IDORDENPROD INT, @FECHA DATETIME, @NUMERO NVARCHAR(13),
	@IDCLIENTE INT, @IDPROYECTO INT, @IDSUBPROYECTO INT

SELECT @IDORDENPROD = INSERTED.IDORDENPROD,
@FECHA = INSERTED.FECHA, @NUMERO = INSERTED.FACTURA,
@IDCLIENTE = INSERTED.IDCLIENTE, @IDPROYECTO = INSERTED.IDPROYECTO,
@IDSUBPROYECTO= INSERTED.IDSUBPROYECTO
FROM INSERTED

UPDATE COMPRA SET
FECHA= @FECHA, 
NUMERO =@NUMERO , 
IDTIPOFACTURA = 10, 
IDCLIENTE = @IDCLIENTE,
IDPROYECTO = @IDPROYECTO, 
IDSUBPROYECTO = @IDSUBPROYECTO
WHERE IDORDENPROD = @IDORDENPROD
GO

ALTER TRIGGER [CREACOMPRA] ON [ORDENPRODUCCION]FOR INSERTAS
DECLARE @IDORDENPROD INT, @FECHA DATETIME, @NUMERO NVARCHAR(13),
	@IDCLIENTE INT, @IDPROYECTO INT, @IDSUBPROYECTO INT, @IDCOMPRA INT

SELECT @IDORDENPROD = INSERTED.IDORDENPROD,
@FECHA = INSERTED.FECHA, @NUMERO = INSERTED.FACTURA,
@IDCLIENTE = INSERTED.IDCLIENTE, @IDPROYECTO = INSERTED.IDPROYECTO,
@IDSUBPROYECTO= INSERTED.IDSUBPROYECTO
FROM INSERTED

INSERT INTO COMPRA(IDORDENPROD, FECHA, NUMERO, IDTIPOFACTURA, IDCLIENTE,
IDPROYECTO, IDSUBPROYECTO)
VALUES(@IDORDENPROD, @FECHA,@NUMERO, 10, @IDCLIENTE,
@IDPROYECTO, @IDSUBPROYECTO)

SELECT @IDCOMPRA = COMPRA.IDCOMPRA FROM COMPRA
WHERE COMPRA.IDORDENPROD = @IDORDENPROD

UPDATE ORDENPRODUCCION SET ORDENPRODUCCION.IDCOMPRA = @IDCOMPRA
WHERE ORDENPRODUCCION.IDORDENPROD = @IDORDENPROD
GO

ALTER TRIGGER [IGUALAFECHA] ON [ASIENTODETALLE] FOR INSERTAS
DECLARE @IDASIENTO INT, @IDDETASIENTO INT
SELECT @IDASIENTO = INSERTED.IDASIENTO, 
	@IDDETASIENTO = INSERTED.IDDETASIENTO FROM INSERTED
UPDATE ASIENTODETALLE 
	SET ASIENTODETALLE.FECHACONF = ASIENTO.FECHA
	FROM ASIENTO INNER JOIN  ASIENTODETALLE
	ON ASIENTODETALLE.IDASIENTO = ASIENTO.IDASIENTO
	WHERE ASIENTO.IDASIENTO = @IDASIENTO
	AND ASIENTODETALLE.IDDETASIENTO = @IDDETASIENTO
	AND ASIENTODETALLE.CONFIRMADO = 0
DELETE ASIENTODETALLE 
WHERE ASIENTODETALLE.IDDETASIENTO = @IDDETASIENTO 
AND ASIENTODETALLE.IDCUENTA = 0 AND ASIENTODETALLE.DEBE = 0 AND ASIENTODETALLE.HABER = 0
GO

ALTER TRIGGER [PAGOACTUALIZA] ON [PAGO] FOR UPDATE, INSERT AS------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
	SELECT @VIDUNICA = i.IDPAGO, @VCOD = i.NUMERO FROM INSERTED i

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'PAGO'
	Set @VCLAVE = 'IdPago'
	Set @vEstado = 2
	If Update(IdPago) Set @vEstado = 1
	Set @vIdTipo = 33
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------

DECLARE @PAGOA FLOAT, @PAGOD FLOAT
SET @PAGOA = 0
SET @PAGOD = 0
SELECT @PAGOA = DELETED.PAGO FROM DELETED 
	WHERE DELETED.PENDIENTE = 0
SELECT @PAGOD = INSERTED.PAGO FROM INSERTED 
	WHERE INSERTED.PENDIENTE = 0

UPDATE COMPRA SET COMPRA.CREDITO = ISNULL(COMPRA.CREDITO, 0) 
  - ISNULL(@PAGOA, 0) + ISNULL(@PAGOD, 0),
  COMPRA.SALDO = ISNULL(COMPRA.SALDO, 0) 
  + ISNULL(@PAGOA, 0) - ISNULL(@PAGOD, 0)
FROM COMPRA, DELETED, INSERTED
WHERE COMPRA.IDCOMPRA = DELETED.IDCOMPRA
GO

ALTER TRIGGER [PAGOBORRA] ON [PAGO] FOR DELETE AS
IF EXISTS(SELECT * FROM SETEO WHERE ISNULL(ELIMINAPAGO, 1) = 0)
BEGIN
	RAISERROR ('NO SE PUEDE ELIMINAR PAGOS. BLOQUEADO EN PROPIEDADES GENERALES', 16, 1)
	ROLLBACK TRANSACTION
	RETURN 
END

DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
SELECT @VIDUNICA = DELETED.IDPAGO FROM DELETED
SELECT @VCOD = DELETED.NUMERO FROM DELETED
INSERT INTO AUDITORIA 
(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA)
VALUES (33, 4, @VCOD, @VIDUNICA)

UPDATE COMPRA SET COMPRA.CREDITO = ISNULL(COMPRA.CREDITO, 0) - ISNULL(DELETED.PAGO, 0),
  COMPRA.SALDO = ISNULL(COMPRA.SALDO, 0) + ISNULL(DELETED.PAGO, 0)
FROM COMPRA INNER JOIN DELETED
ON COMPRA.IDCOMPRA = DELETED.IDCOMPRA
WHERE DELETED.PENDIENTE = 0
GO

ALTER TRIGGER [PAGOINSERTA] ON [PAGO] FOR INSERTAS
UPDATE COMPRA SET COMPRA.CREDITO = 
    ISNULL(COMPRA.CREDITO, 0) + ISNULL(INSERTED.PAGO, 0),
    COMPRA.SALDO = ISNULL(COMPRA.SALDO, 0) - ISNULL(INSERTED.PAGO, 0)
FROM COMPRA INNER JOIN INSERTED
ON COMPRA.IDCOMPRA = INSERTED.IDCOMPRA
WHERE INSERTED.PENDIENTE = 0
GO

ALTER TRIGGER [PROYECTOACTUALIZA] ON [PROYECTO] FOR INSERT ASSET NOCOUNT ON;------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
	SELECT @VIDUNICA = i.IdProyecto, @VCOD = i.CentroCosto FROM INSERTED i

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'PROYECTO'
	Set @VCLAVE = 'IDPROYECTO'
	Set @vEstado = 2
--	If Update(IdProyecto) Set @vEstado = 1
	Set @vIdTipo = 60
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------
GO

ALTER TRIGGER [RETENCIONACTUALIZA] ON [RETENCION] FOR UPDATE, INSERT AS------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 0)
Begin
	DECLARE @VIDUNICA INT, @VCOD VARCHAR(20), @VTIPO INT
	SELECT @VIDUNICA = i.IDRETENCION, @VCOD = i.CODIGO, @VTIPO = i.INGRESOEGRESO FROM INSERTED i
	SET @VTIPO = @VTIPO + 47

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'RETENCION'
	Set @VCLAVE = 'IDRETENCION'
	Set @vEstado = 2
	Set @vIdTipo = @VTIPO
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS' --AND SUBSTRING(@VCOL,1,8) <>'FECHAEDI'
		BEGIN
		SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
		' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
		+ CAST(@VIDUNICA AS VARCHAR(20))
		EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
		IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
			INSERT INTO AUDITORIA 
			(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
			VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
		SET @IDCOL = 1
		SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------
UPDATE C SET C.RETENIDO = I.IVARETENIDO1 +
	I.IVARETENIDO + I.RENTARETENIDA1 + I.RENTARETENIDA
FROM COMPRA C INNER JOIN INSERTED I
ON C.IDCOMPRA = I.IDCOMPRA
GO

ALTER TRIGGER [RETENCIONBORRA] ON [RETENCION] FOR DELETE AS
DECLARE @VIDUNICA INT, @VCOD VARCHAR(20), @VTIPO INT, @IDPAGOLOTE INT
SELECT @VIDUNICA = DELETED.IDRETENCION FROM DELETED
SELECT @VCOD = DELETED.CODIGO FROM DELETED
SELECT @VTIPO = INGRESOEGRESO, @IDPAGOLOTE = IDPAGOLOTE FROM DELETED
SET @VTIPO = @VTIPO + 47

INSERT INTO AUDITORIA 
(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA)
VALUES (@VTIPO, 4, @VCOD, @VIDUNICA)

IF ISNULL(@IDPAGOLOTE, 0) > 0
BEGIN
	UPDATE COMPRA SET COMPRA.RETENIDO =0, COMPRA.IDPAGOLOT = 0,
		COMPRA.SALDO = COMPRA.SALDO + COMPRA.RETENIDO
		WHERE COMPRA.IDPAGOLOT = @IDPAGOLOTE
END
ELSE
BEGIN
	UPDATE C SET C.RETENIDO =0, C.SALDO = ISNULL(C.SALDO, 0) + ISNULL(D.RENTARETENIDA, 0)
	+ ISNULL(D.RENTARETENIDA1, 0) + ISNULL(D.IVARETENIDO, 0) + ISNULL(D.IVARETENIDO1, 0)
	FROM COMPRA C INNER JOIN DELETED D
	ON C.IDCOMPRA = D.IDCOMPRA
END
GO

ALTER TRIGGER [RETENCIONINSERTA] ON [RETENCION] FOR INSERTAS
return
GO

ALTER TRIGGER [RETENCIONIVABORRA] ON [DBO].[RETENCIONIVA] FOR DELETE AS
DECLARE @VIDUNICA INT, @VCOD VARCHAR(20)
SELECT @VIDUNICA = DELETED.IDRETIVA FROM DELETED
SELECT @VCOD = DELETED.CODIGO FROM DELETED
INSERT INTO AUDITORIA 
(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA)
VALUES (59, 4, @VCOD, @VIDUNICA)



GO

ALTER TRIGGER [RETENCIONIVAEDITA] ON [DBO].[RETENCIONIVA] FOR UPDATEAS
------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VCOD = Codigo, @VIDUNICA = IDRETIVA FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'RETENCIONIVA'
	Set @VCLAVE = 'IDRETIVA'
	Set @vEstado = 2
	If Update(IDRETIVA) Set @vEstado = 1
	Set @vIdTipo = 59
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------




GO

ALTER TRIGGER [RETENCIONIVANUEVO] ON [DBO].[RETENCIONIVA] FOR INSERTAS
------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VCOD = Codigo, @VIDUNICA = IDRETIVA FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'RETENCIONIVA'
	Set @VCLAVE = 'IDRETIVA'
	Set @vEstado = 2
	If Update(IDRETIVA) Set @vEstado = 1
	Set @vIdTipo = 59
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------
GO

ALTER TRIGGER [SALDOCOSTO] ON DBO.DETCOMPRA FOR UPDATE AS
DECLARE @VARTD INT, @VCANTD INT, @VSIGNO INT, @ACTSALDO BIT, @ACTCOSTO BIT
SELECT @ACTSALDO = ACTUALIZASALDO, @ACTCOSTO = ACTUALIZACOSTO FROM SETEOF
IF ISNULL(@ACTSALDO, 1) = 0 RETURN

SELECT @VARTD = DELETED.IDARTICULO, @VCANTD = DELETED.CANTIDAD,
@VSIGNO = DELETED.SIGNO FROM DELETED INNER JOIN INSERTED ON
DELETED.IDCOMPRA = INSERTED.IDCOMPRA WHERE DELETED.IDARTICULO <> INSERTED.IDARTICULO
UPDATE ARTICULO SET SALDO = SALDO - ISNULL(@VCANTD, 0) * @VSIGNO WHERE IDARTICULO = @VARTD
DECLARE @VIDCOMPRA INT
SELECT @VIDCOMPRA = INSERTED.IDCOMPRA FROM INSERTED
IF ISNULL(@ACTCOSTO, 1) = 1 EXEC SALDOCOSTOCOMPRA @VIDCOMPRA
GO

ALTER TRIGGER [SALDOCOSTOI] ON DBO.DETCOMPRA FOR INSERTAS
DECLARE @VARTD INT, @VCANTD INT, @VSIGNO INT, @VBODEGA INT
DECLARE @VIDCOMPRA INT, @ACTSALDO BIT, @ACTCOSTO BIT
SELECT @ACTSALDO = ACTUALIZASALDO, @ACTCOSTO = ACTUALIZACOSTO FROM SETEOF
IF ISNULL(@ACTSALDO, 1) = 0 RETURN

SELECT @VARTD = INSERTED.IDARTICULO, @VCANTD = INSERTED.CANTIDAD,
@VSIGNO = COMPRANUMERO.SIGNO, @VBODEGA = COMPRA.BODEGA,
@VIDCOMPRA = INSERTED.IDCOMPRA FROM INSERTED INNER JOIN COMPRA 
ON COMPRA.IDCOMPRA = INSERTED.IDCOMPRA INNER JOIN COMPRANUMERO
ON COMPRA.IDTIPOFACTURA = COMPRANUMERO.IDTIPOFACTURA 

UPDATE ARTICULO SET SALDO = SALDO + ISNULL(@VCANTD, 0) * @VSIGNO 
	WHERE IDARTICULO = @VARTD

UPDATE DETCOMPRA SET DETCOMPRA.SIGNO = COMPRANUMERO.SIGNO
FROM DETCOMPRA INNER JOIN COMPRA ON DETCOMPRA.IDCOMPRA = COMPRA.IDCOMPRA
INNER JOIN COMPRANUMERO ON COMPRA.IDTIPOFACTURA = COMPRANUMERO.IDTIPOFACTURA
WHERE DETCOMPRA.IDCOMPRA = @VIDCOMPRA AND DETCOMPRA.SIGNO <> COMPRANUMERO.SIGNO

IF ISNULL(@ACTCOSTO, 1) = 1 EXEC SALDOCOSTOCOMPRA @VIDCOMPRA
GO

ALTER TRIGGER [DBO].[SALDOCXCACTUALIZA] ON [DBO].[COMPRA] FOR UPDATE ASDECLARE @IDCLIENTED INT, @ICONTADOCREDD INT, @FSALDOD FLOAT, 
	@IDCOMPRA INT, @IDTIPOFACTURAD INT, @PORCIVA FLOAT,
	@DECREDONDEO INT, @BORRAD BIT, @IDASIENTOD INT,
	@RETENIDO FLOAT, @Bodega int

DECLARE @VMOSTRARBODEGA BIT, @IDPAGOLOT INT
SELECT @VMOSTRARBODEGA = SETEOF.VERBODEGA FROM SETEOF
IF @VMOSTRARBODEGA = 0
    UPDATE DETCOMPRA SET DETCOMPRA.BODEGA =  INSERTED.BODEGA
	FROM INSERTED INNER JOIN DETCOMPRA ON INSERTED.IDCOMPRA = DETCOMPRA.IDCOMPRA
	WHERE DETCOMPRA.IDCOMPRA = INSERTED.IDCOMPRA

SELECT @PORCIVA = SETEOF.IVA, @DECREDONDEO = SETEOF.DECREDONDEO 
	FROM SETEOF WHERE IDSETEOF = 1

SET @RETENIDO = 0
SELECT @IDCLIENTED =INSERTED.IDCLIENTE, 
	@IDASIENTOD = INSERTED.IDASIENTO,
	@ICONTADOCREDD= INSERTED.CONTADOCREDITO,
	@FSALDOD =ISNULL(INSERTED.SUBTOTALIVA, 0) 
	+ ISNULL(INSERTED.SUBTOTALEXCENTO, 0) 
	- (ISNULL(INSERTED.DESC1, 0) 
	+ ISNULL(INSERTED.DESC2, 0) 
	+ ISNULL(INSERTED.DESC3, 0)
	+ ISNULL(INSERTED.DESC4, 0) ) 
	- ISNULL(INSERTED.RETENIDO, 0) 
	- ISNULL(INSERTED.CONTADO, 0) 
	- ISNULL(INSERTED.CREDITO, 0) 
	+ ISNULL(INSERTED.IVA, 0)
	+ ISNULL(INSERTED.Servicio, 0)
	+ ISNULL(INSERTED.Propina, 0)
	+ ISNULL(INSERTED.ICE, 0), @Bodega = Inserted.Bodega,
	@IDTIPOFACTURAD = INSERTED.IDTIPOFACTURA, @BORRAD = INSERTED.BORRAR,
	@IDCOMPRA =INSERTED.IDCOMPRA, @IDPAGOLOT = INSERTED.IDPAGOLOT,
	@RETENIDO = INSERTED.RETENIDO FROM INSERTED

UPDATE Serie SET Bodega = @Bodega WHERE idCompra = @idCompra

IF ISNULL(@IDPAGOLOT, 0) = 0
	SELECT @RETENIDO = ISNULL(RENTARETENIDA, 0) 
		+ ISNULL(RENTARETENIDA1, 0) 
		+ ISNULL(IVARETENIDO, 0) 
		+ ISNULL(IVARETENIDO1, 0) 
		FROM RETENCION
		WHERE RETENCION.IDCOMPRA = @IDCOMPRA

UPDATE COMPRA SET 
DESCUENTO = ISNULL(DESC1,0) + ISNULL(DESC3, 0),
DESCUENTO0 = ISNULL(DESC2, 0) + ISNULL(DESC4, 0),
RETENIDO = ISNULL(@RETENIDO, 0),
TOTAL = ISNULL(SUBTOTALIVA, 0) + ISNULL(SUBTOTALEXCENTO, 0) 
 - (ISNULL(DESC1, 0) + ISNULL(DESC2, 0)
 + ISNULL(DESC3, 0) + ISNULL(DESC4, 0) ) 
 + ISNULL(ICE, 0)
 + IVA + IsNull(Servicio, 0) + IsNull(Propina, 0)
FROM COMPRA
WHERE COMPRA.IDCOMPRA = @IDCOMPRA

DECLARE @IDCLIENTEA INT, @ICONTADOCREDA INT, @FSALDOA FLOAT, 
	@IDTIPOFACTURAA INT, @BORRAA BIT, @IDASIENTOA INT
SELECT @IDCLIENTEA =DELETED.IDCLIENTE, @ICONTADOCREDA= DELETED.CONTADOCREDITO,
	@IDASIENTOA = DELETED.IDASIENTO,
	@FSALDOA = ISNULL(DELETED.TOTAL, 0) 
	-ISNULL(DELETED.RETENIDO, 0) 
	- ISNULL(DELETED.CONTADO, 0) 
	- ISNULL(DELETED.CREDITO, 0) , 
	@IDTIPOFACTURAA = DELETED.IDTIPOFACTURA, @BORRAA  = DELETED.BORRAR  
	FROM DELETED

EXEC COMPRASALDOCLIENTEBORRA @FSALDOA, @IDCOMPRA, 
	@ICONTADOCREDA, @IDCLIENTEA, @IDTIPOFACTURAA, @BORRAA

EXEC COMPRASALDOCLIENTEINS @FSALDOD, @IDCOMPRA, 
	@ICONTADOCREDD, @IDCLIENTED, @IDTIPOFACTURAD, @BORRAD

-- ACTUALIZA IDASIENTO EN RETENCION SOLO CUANDO CAMBIA
IF @IDASIENTOD <> @IDASIENTOA
BEGIN
	UPDATE RETENCION SET IDASIENTO = @IDASIENTOD
	WHERE IDCOMPRA = @IDCOMPRA
END

-- ANALISIS DE ANULADO
IF EXISTS (SELECT * FROM INSERTED INNER JOIN DELETED 
	ON INSERTED.IDCOMPRA = DELETED.IDCOMPRA
	WHERE DELETED.BORRAR <> INSERTED.BORRAR
	AND INSERTED.BORRAR = 1)
BEGIN
--	PRINT 'MODIFICADO BORRAR'
	EXEC SALDOARTICULOANULADO @IDCOMPRA, 1
END
IF EXISTS (SELECT * FROM INSERTED INNER JOIN DELETED 
	ON INSERTED.IDCOMPRA = DELETED.IDCOMPRA
	WHERE DELETED.BORRAR <> INSERTED.BORRAR
	AND INSERTED.BORRAR = 0)
BEGIN
--	PRINT 'MODIFICADO RESTAURAR'
	EXEC SALDOARTICULOANULADO @IDCOMPRA, -1
END
-- FIN DE ANULADOS

-- EDITA AUDITORIA

------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VIDUNICA INT, @VCOD VARCHAR(20), @VTIPO INT
	SELECT @VIDUNICA = i.IDCOMPRA, @VCOD = i.NUMERO, @VTIPO = i.IDTIPOFACTURA FROM INSERTED i

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'COMPRA'
	Set @VCLAVE = 'IDCOMPRA'
	Set @vEstado = 2
	If Update(IDCOMPRA) Set @vEstado = 1
	Set @vIdTipo = @vTipo
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------
GO

ALTER TRIGGER [SALDOCXCBORRAR] ON [COMPRA]FOR DELETE AS
IF EXISTS(SELECT * FROM SETEO WHERE ISNULL(ELIMINAFACTURA, 0) = 1)
BEGIN
	RAISERROR ('NO SE PUEDE ELIMINAR FACTURAS. BLOQUEADO EN PROPIEDADES GENERALES', 16, 1)
	ROLLBACK TRANSACTION
	RETURN 
END
-- DISMINUYE EL SALDO GLOBAL DEL CLIENTE = TOTAL - RETENIDO
DECLARE @IDCLIENTE INT, @ICONTADOCRED INT, @FSALDO FLOAT, 
	@IDTIPOFACTURA INT, @IDCOMPRA INT, @BORRA BIT
SELECT @IDCLIENTE =DELETED.IDCLIENTE, @ICONTADOCRED= DELETED.CONTADOCREDITO,
	@FSALDO = ISNULL(DELETED.TOTAL, 0) 
	- ISNULL(DELETED.RETENIDO, 0) 
	- ISNULL(DELETED.CONTADO, 0) 
	- ISNULL(DELETED.CREDITO, 0) , 
	@IDTIPOFACTURA = DELETED.IDTIPOFACTURA,
	@IDCOMPRA = DELETED.IDCOMPRA, @BORRA = DELETED.BORRAR
	FROM DELETED

EXEC COMPRASALDOCLIENTEBORRA @FSALDO, @IDCOMPRA, 
	@ICONTADOCRED, @IDCLIENTE, @IDTIPOFACTURA, @BORRA

-- AUDITORIA DE BORRADO
DECLARE @VIDUNICA INT, @VCOD VARCHAR(20), @VTIPO INT
SELECT @VTIPO = DELETED.IDTIPOFACTURA FROM DELETED
SELECT @VIDUNICA = DELETED.IDCOMPRA FROM DELETED
SELECT @VCOD = DELETED.NUMERO FROM DELETED
INSERT INTO AUDITORIA 
(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA)
VALUES (@VTIPO, 4, @VCOD, @VIDUNICA)
commit transaction GrabaFactura
GO

ALTER TRIGGER [DBO].[SALDOCXCINSERTA] ON [DBO].[COMPRA] FOR INSERT ASBegin Transaction GrabaFactura

DECLARE @VIDUNICA INT, @VCOD VARCHAR(20), @VTIPO INT, @IdDocumento int
SELECT @VIDUNICA = INSERTED.IDCOMPRA FROM INSERTED
SELECT @VCOD = INSERTED.NUMERO FROM INSERTED
SELECT @VTIPO = INSERTED.IDTIPOFACTURA FROM INSERTED
SELECT @IdDocumento = INSERTED.IdComprobante FROM INSERTED
IF @IdDocumento = 15 Set @IdDocumento = 1
IF EXISTS(SELECT * FROM FACTURANUMERO WHERE ESTACION = HOST_NAME()
	AND IDTIPOFACTURA = @vTipo And IsNull(AutoImpresor, 0) = 1)
Begin
	exec dbo.FacturaNumeroEstacion @vTipo, @VCod output, @idDocumento
	Declare @FechaCad DateTime, @AutFactura nVarChar(20)
	Select @FechaCad = Seteo.SriCaduca From Seteo
	Select @AutFactura = Autorizacion From FacturaNumero WHERE ESTACION = HOST_NAME()
	AND IDTIPOFACTURA = @vTipo And IsNull(AutoImpresor, 0) = 1
	update Compra set NUMERO = @vCod, AutoImpSRI = 1, FechaCaducidad = @FechaCad,
		AutFactura = @AutFactura
		where Compra.IDCOMPRA = @VIDUNICA
End

------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'COMPRA'
	Set @VCLAVE = 'IDCOMPRA'
	Set @vEstado = 2
	If Update(IDCOMPRA) Set @vEstado = 1
	Set @vIdTipo = @vTipo
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------

DECLARE @IDCLIENTE INT, @ICONTADOCRED INT, @FSALDO FLOAT, 
	@IDCOMPRA INT, @IDTIPOFACTURA INT, @BORRA BIT
SELECT @IDCLIENTE = INSERTED.IDCLIENTE, 
	@ICONTADOCRED= INSERTED.CONTADOCREDITO,
	@FSALDO = ISNULL(INSERTED.TOTAL, 0)
	 -ISNULL(INSERTED.RETENIDO, 0)
	- ISNULL(INSERTED.CONTADO, 0) 
	- ISNULL(INSERTED.CREDITO, 0), 
	@IDTIPOFACTURA = INSERTED.IDTIPOFACTURA , 
	@IDCOMPRA = INSERTED.IDCOMPRA, 
	@BORRA = INSERTED.BORRAR FROM INSERTED

EXEC COMPRASALDOCLIENTEINS @FSALDO, @IDCOMPRA, 
	@ICONTADOCRED, @IDCLIENTE, @IDTIPOFACTURA, @BORRA

DECLARE @VMOSTRARBODEGA BIT
SELECT @VMOSTRARBODEGA = SETEOF.VERBODEGA FROM SETEOF
IF @VMOSTRARBODEGA = 0
    UPDATE DETCOMPRA SET DETCOMPRA.BODEGA =  Inserted.BODEGA
	From Inserted INNER Join DetCompra On Inserted.idCompra = DetCompra.idCompra
	Where DetCompra.idCompra = Inserted.IdCompra

commit transaction GrabaFactura




GO

ALTER TRIGGER [SERIEACTUALIZA]   ON  [SERIE] FOR UPDATEAS 
BEGIN
	SET NOCOUNT ON;
	DECLARE @SERIE NVARCHAR(20), @DETALLE NVARCHAR(50), @IDORIGEN INT
	SELECT @SERIE = SERIE, @DETALLE = DETALLE,
		@IDORIGEN = IDSERIE FROM INSERTED 

	UPDATE SERIE SET SERIE = @SERIE, DETALLE = @DETALLE
		WHERE IDORIGEN = @IDORIGEN
END
GO

ALTER TRIGGER [SERIEBORRAR] ON [SERIE]   FOR DELETEAS 
BEGIN
	SET NOCOUNT ON
	DECLARE @IDORIGEN INT
	SELECT @IDORIGEN = DELETED.IDORIGEN FROM DELETED
	UPDATE SERIE SET DISPONIBLE = 1 WHERE IDSERIE = @IDORIGEN
END
GO

ALTER TRIGGER [SERIEINSERTA]   ON  [SERIE] FOR INSERTAS 
BEGIN
	SET NOCOUNT ON;
	DECLARE @IDCOMPRA INT, @BODEGA INT
	SELECT @IDCOMPRA = IDCOMPRA FROM INSERTED 
	SELECT @BODEGA = COMPRA.BODEGA FROM COMPRA 
		WHERE IDCOMPRA = @IDCOMPRA

	UPDATE SERIE SET BODEGA = @BODEGA
		WHERE IDCOMPRA = @IDCOMPRA
END
GO

ALTER TRIGGER [SETEOCEDITA] ON [SETEOC]   FOR UPDATE AS ------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VCOD = 'SETEOC', @VIDUNICA = IDSETEOC FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'SETEOC'
	Set @VCLAVE = 'IDSETEOC'
	Set @vEstado = 2
	If Update(IDSETEOC) Set @vEstado = 1
	Set @vIdTipo = 43
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------
GO

ALTER TRIGGER [SETEOEDITA] ON [SETEO]   FOR UPDATE AS ------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VCOD = 'SETEO', @VIDUNICA = IDSETEO FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'SETEO'
	Set @VCLAVE = 'IDSETEO'
	Set @vEstado = 2
	If Update(IDSETEO) Set @vEstado = 1
	Set @vIdTipo = 42
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------
GO

ALTER TRIGGER [SETEOFEDITA] ON [SETEOF]   FOR UPDATE AS ------- Auditoria -----------
If Exists(SELECT * FROM SETEO Where AUDITORIA = 1)
Begin
	DECLARE @VCOD VARCHAR(20), @VIDUNICA INT
	SELECT @VCOD = 'SETEOF', @VIDUNICA = IDSETEOF FROM INSERTED

	Declare @VTABLA VARCHAR(100), @VCLAVE VARCHAR(100), @vEstado int, @vIdTipo int
	DECLARE @IDCOL BIGINT, @VCOL NVARCHAR(40), @VCOMPARA NVARCHAR(500), 
	@IDCOLN BIGINT, @IDPOS INT, @VSALIDA NVARCHAR(100)
	Set @VTABLA = 'SETEOF'
	Set @VCLAVE = 'IDSETEOF'
	Set @vEstado = 2
	If Update(IDSETEOF) Set @vEstado = 1
	Set @vIdTipo = 44
	SET @IDCOL = 1
	SET @IDPOS = 1
	SET @IDCOLN = 1

	SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), 1)
	WHILE @VCOL IS NOT NULL Or @IdPos < 3
	BEGIN
		IF (SUBSTRING(COLUMNS_UPDATED(), @IDPOS, 1) & @IDCOL) > 0 AND SUBSTRING(@VCOL,1,3) <>'UPS'
		BEGIN
			SET @VCOMPARA = 'SELECT @VSALIDA=' + @VCOL + 
				' FROM ' + @VTABLA + ' WHERE ' + @VCLAVE + ' = '
				+ CAST(@VIDUNICA AS VARCHAR(20))
			EXEC SP_EXECUTESQL  @VCOMPARA, N'@VSALIDA NVARCHAR(100) OUTPUT', @VSALIDA OUTPUT
			IF @VESTADO = 2 OR (@VSALIDA IS NOT NULL AND @VSALIDA <> '0')
				INSERT INTO AUDITORIA 
				(IDTIPOAUDITA, IDAUDITAESTADO, CODIGO, IDUNICA, CAMPO, VALOR)
				VALUES (@VIDTIPO, @VESTADO, @VCOD, @VIDUNICA, @VCOL, @VSALIDA)
		END
		SET @IDCOL = @IDCOL * 2
		SET @IDCOLN = @IDCOLN + 1
		IF @IDCOL >= 256     
		BEGIN
			SET @IDCOL = 1
			SET @IDPOS = @IDPOS + 1
		END
		SELECT @VCOL = COL_NAME(OBJECT_ID(@VTABLA), @IDCOLN)
	END
End
------- Fin de Auditoria -----------
GO

