//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2494
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=1.1.4322.2494.
// 
namespace Latinium.com.solucionfactible {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TimbradoSoap11Binding", Namespace="http://timbrado.ws.cfdi.solucionfactible.com")]
    public class Timbrado : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Timbrado() {
            this.Url = "https://solucionfactible.com/ws/services/Timbrado.TimbradoHttpsSoap11Endpoint/";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:cancelarPorNotaCredito", RequestNamespace="http://timbrado.ws.cfdi.solucionfactible.com", ResponseNamespace="http://timbrado.ws.cfdi.solucionfactible.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public CFDIResultadoCertificacion cancelarPorNotaCredito([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string uuid, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] System.Byte[] derCertCSD, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] System.Byte[] derKeyCSD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string contrasenaCSD) {
            object[] results = this.Invoke("cancelarPorNotaCredito", new object[] {
                        usuario,
                        password,
                        uuid,
                        derCertCSD,
                        derKeyCSD,
                        contrasenaCSD});
            return ((CFDIResultadoCertificacion)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincancelarPorNotaCredito(string usuario, string password, string uuid, System.Byte[] derCertCSD, System.Byte[] derKeyCSD, string contrasenaCSD, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("cancelarPorNotaCredito", new object[] {
                        usuario,
                        password,
                        uuid,
                        derCertCSD,
                        derKeyCSD,
                        contrasenaCSD}, callback, asyncState);
        }
        
        /// <remarks/>
        public CFDIResultadoCertificacion EndcancelarPorNotaCredito(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CFDIResultadoCertificacion)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:cancelarViaCSDAlmacenado", RequestNamespace="http://timbrado.ws.cfdi.solucionfactible.com", ResponseNamespace="http://timbrado.ws.cfdi.solucionfactible.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public CFDICancelacion cancelarViaCSDAlmacenado([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute("uuids", IsNullable=true)] string[] uuids) {
            object[] results = this.Invoke("cancelarViaCSDAlmacenado", new object[] {
                        usuario,
                        password,
                        rfcEmisor,
                        uuids});
            return ((CFDICancelacion)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincancelarViaCSDAlmacenado(string usuario, string password, string rfcEmisor, string[] uuids, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("cancelarViaCSDAlmacenado", new object[] {
                        usuario,
                        password,
                        rfcEmisor,
                        uuids}, callback, asyncState);
        }
        
        /// <remarks/>
        public CFDICancelacion EndcancelarViaCSDAlmacenado(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CFDICancelacion)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:enviarSolicitudCancelacion", RequestNamespace="http://timbrado.ws.cfdi.solucionfactible.com", ResponseNamespace="http://timbrado.ws.cfdi.solucionfactible.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public CFDICancelacion enviarSolicitudCancelacion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] System.Byte[] solicitudCancelacion) {
            object[] results = this.Invoke("enviarSolicitudCancelacion", new object[] {
                        usuario,
                        password,
                        solicitudCancelacion});
            return ((CFDICancelacion)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginenviarSolicitudCancelacion(string usuario, string password, System.Byte[] solicitudCancelacion, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("enviarSolicitudCancelacion", new object[] {
                        usuario,
                        password,
                        solicitudCancelacion}, callback, asyncState);
        }
        
        /// <remarks/>
        public CFDICancelacion EndenviarSolicitudCancelacion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CFDICancelacion)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:cancelar", RequestNamespace="http://timbrado.ws.cfdi.solucionfactible.com", ResponseNamespace="http://timbrado.ws.cfdi.solucionfactible.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public CFDICancelacion cancelar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute("uuids", IsNullable=true)] string[] uuids, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] System.Byte[] derCertCSD, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] System.Byte[] derKeyCSD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string contrasenaCSD) {
            object[] results = this.Invoke("cancelar", new object[] {
                        usuario,
                        password,
                        uuids,
                        derCertCSD,
                        derKeyCSD,
                        contrasenaCSD});
            return ((CFDICancelacion)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begincancelar(string usuario, string password, string[] uuids, System.Byte[] derCertCSD, System.Byte[] derKeyCSD, string contrasenaCSD, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("cancelar", new object[] {
                        usuario,
                        password,
                        uuids,
                        derCertCSD,
                        derKeyCSD,
                        contrasenaCSD}, callback, asyncState);
        }
        
        /// <remarks/>
        public CFDICancelacion Endcancelar(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CFDICancelacion)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:timbrarBase64", RequestNamespace="http://timbrado.ws.cfdi.solucionfactible.com", ResponseNamespace="http://timbrado.ws.cfdi.solucionfactible.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public CFDICertificacion timbrarBase64([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cfdiBase64, bool zip, [System.Xml.Serialization.XmlIgnoreAttribute()] bool zipSpecified) {
            object[] results = this.Invoke("timbrarBase64", new object[] {
                        usuario,
                        password,
                        cfdiBase64,
                        zip,
                        zipSpecified});
            return ((CFDICertificacion)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegintimbrarBase64(string usuario, string password, string cfdiBase64, bool zip, bool zipSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("timbrarBase64", new object[] {
                        usuario,
                        password,
                        cfdiBase64,
                        zip,
                        zipSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public CFDICertificacion EndtimbrarBase64(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CFDICertificacion)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:timbrar", RequestNamespace="http://timbrado.ws.cfdi.solucionfactible.com", ResponseNamespace="http://timbrado.ws.cfdi.solucionfactible.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public CFDICertificacion timbrar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)] System.Byte[] cfdi, bool zip, [System.Xml.Serialization.XmlIgnoreAttribute()] bool zipSpecified) {
            object[] results = this.Invoke("timbrar", new object[] {
                        usuario,
                        password,
                        cfdi,
                        zip,
                        zipSpecified});
            return ((CFDICertificacion)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begintimbrar(string usuario, string password, System.Byte[] cfdi, bool zip, bool zipSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("timbrar", new object[] {
                        usuario,
                        password,
                        cfdi,
                        zip,
                        zipSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public CFDICertificacion Endtimbrar(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CFDICertificacion)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:cancelarBase64", RequestNamespace="http://timbrado.ws.cfdi.solucionfactible.com", ResponseNamespace="http://timbrado.ws.cfdi.solucionfactible.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public CFDICancelacion cancelarBase64([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute("uuids", IsNullable=true)] string[] uuids, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string derCertCSDBase64, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string derKeyCSDBase64, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string contrasenaCSD) {
            object[] results = this.Invoke("cancelarBase64", new object[] {
                        usuario,
                        password,
                        uuids,
                        derCertCSDBase64,
                        derKeyCSDBase64,
                        contrasenaCSD});
            return ((CFDICancelacion)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincancelarBase64(string usuario, string password, string[] uuids, string derCertCSDBase64, string derKeyCSDBase64, string contrasenaCSD, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("cancelarBase64", new object[] {
                        usuario,
                        password,
                        uuids,
                        derCertCSDBase64,
                        derKeyCSDBase64,
                        contrasenaCSD}, callback, asyncState);
        }
        
        /// <remarks/>
        public CFDICancelacion EndcancelarBase64(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CFDICancelacion)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com/xsd")]
    public class CFDIResultadoCertificacion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cadenaOriginal;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string certificadoSAT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public System.Byte[] cfdiTimbrado;
        
        /// <remarks/>
        public System.DateTime fechaTimbrado;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaTimbradoSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mensaje;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public System.Byte[] qrCode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string selloSAT;
        
        /// <remarks/>
        public int status;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uuid;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string versionTFD;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com/xsd")]
    public class CFDICertificacion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mensaje;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resultados", IsNullable=true)]
        public CFDIResultadoCertificacion[] resultados;
        
        /// <remarks/>
        public int status;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com/xsd")]
    public class CFDIResultadoCancelacion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mensaje;
        
        /// <remarks/>
        public int status;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string statusUUID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uuid;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com/xsd")]
    public class CFDICancelacion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mensaje;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resultados", IsNullable=true)]
        public CFDIResultadoCancelacion[] resultados;
        
        /// <remarks/>
        public int status;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified;
    }
}
